---
title: "First Year Exam Q15"
author: "Pham Thuy Tien Vo - PID: A59010610"
date: "7/13/2022"
output:
  pdf_document: default
  html_document: default
---
```{r}
# To read the database on COVID-19 variants file 
variant <- read.csv("covid19_variants.csv")
head(variant)
```

```{r}
library("ggplot2")
library(lubridate)

#To remove Total and Other rows 
variant1 <- variant[!(variant$variant_name=="Total" | variant$variant_name=="Other"),]
#View(variant1)

#To convert date to a format that is compatible for R
variant1$date <- ymd(variant1$date)

#To plot the data
ggplot(variant1, aes(date, percentage, col=variant_name)) +
  labs(caption ="Data Source: <https://www.cdph.ca.gov/>", x="", y="Percentage of sequenced speciments", title="Covid-19 Variants in California") + #To add labels for axis
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") + # To increase increment for x-axis 
  theme_bw() + # To change the setting for gridline and background
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) + #To turn the x-axis labels for 60 degree
  theme(legend.title= element_blank()) + # To get rid of legend title
  geom_line() # To draw a line graph
```

